version: "3.3"
services:
  app:
    build: .
    restart: always

  postgres12:
    image: postgres:12
    environment:
      POSTGRES_DB: "juicelife_dashboards"
      POSTGRES_USER: "admin_juicelife"
      POSTGRES_PASSWORD: "mypassword"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres12:/var/lib/postgresql/data

volumes:
  postgres12:
    driver: local



