version: "3.3"
services:
  app:
    build: .
    restart: always

  postgres12:
    image: postgres:12
    environment:
      POSTGRES_DB: "coraltravel"
      POSTGRES_USER: "db_user"
      POSTGRES_PASSWORD: "mypassword"
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432"
    volumes:
      - ./postgres12:/var/lib/postgresql/data

volumes:
  postgres12:
    driver: local



