version: '3'
x-airflow-common:
  &airflow-common
  build:
    context: .
    dockerfile: ./jl_airflow/Dockerfile
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://$POSTGRES_USER:$POSTGRES_PASSWORD@194.67.111.233/$POSTGRES_DB
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__WEBSERVER__SECRET_KEY: 'albatros'
    PYTHONPATH: "/app"

  user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-50000}"

services:
  telegram_bot:
    build: .
    ports:
      - "2903:2903"
    restart: always

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always


  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always


  airflow-init:
    <<: *airflow-common
    command: version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: $AIRFLOW_USERNAME
      _AIRFLOW_WWW_USER_PASSWORD: $AIRFLOW_PASSWORD


volumes:
    postgres12:
      driver: local
